name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: carsonwltz
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: America/Chicago
          plugin_calendar: yes
          plugin_calendar_limit: 0
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
