name: Waka Readme
on:
  #Run at minute 0 past the hour, every 12 hours
  schedule: [{ cron: "0 */12 * * *" }]
  #Run workflow manually
  workflow_dispatch:
  #Run workflow when pushing on master/main
  # push: { branches: ["master", "main"] }
jobs:
  waka-readme-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          #Token
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          #Configure
          LOCALE: "en"
          SECTION_NAME: "waka"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_OS: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_TIMEZONE: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_UPDATED_DATE: "True"
          SYMBOL_VERSION: "1"
